### ISSUE TITLE
Linux环境下的Burp

### ISSUE THREAD

**Issue by zzgxpyy** [yuyan-sec/Doraemon#1]
在Linux 环境下测试 V2022.3.7 没有生成目录和exp.yaml 、 payload.yaml文件。 
直接调用插件，无显示。

**Comment by yuyan-sec** [comment]
@zzgxpyy 查看一下目录是不是有写入权限。我用 kali 用户启动自带的Burpsuite就是没权限写入，使用 sudo 启动BurpSuite就好了。
