### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Admin123456-check** [yuyan-sec/Doraemon#11]
1、不支持HTTP/2协议的转换，会报错
2、{{Cookie}}现在好像都是替换成 Cookie: test=test

**Comment by yuyan-sec** [comment]
@Admin123456-check 什么 HTTP/2的转换？没有获取到Cookie 的时候默认的是 test=test

**Comment by Admin123456-check** [comment]
请求包，有些是HTTP/1.1 可以正常转换。有些是HTTP/2会失败

**Comment by yuyan-sec** [comment]
@Admin123456-check 不太懂你的意思，你截下图或加我微信，我的用户名就是WX

**Comment by yuyan-sec** [comment]
![image](https://github.com/user-attachments/assets/9a2b7b6e-975f-48c6-9d3b-c4005299e79a)

把Repeater 设置默认 http 1 就好了，http/2不知道要怎么解决
