### ISSUE TITLE
求增

### ISSUE THREAD

**Issue by kingofpeoples** [yuyan-sec/Doraemon#3]
目前的exp和payload配置只能一级目录管理而不是根据配置目录层次自动分级，不易于类型分别管理，大佬可以新增根据配置自动分级管理呀

**Comment by yuyan-sec** [comment]
@kingofpeoples [v3版本](https://github.com/yuyan-sec/Doraemon/releases/tag/v3)  已经可以3个层级了：WebShell -> 蚁剑 -> php  ，没办法根据配置自动分级，我觉得这样刚刚好。

**Comment by yuyan-sec** [comment]
@kingofpeoples 现在可以利用目录来匹配层级了
