### ISSUE TITLE
burp插件安装显示错误

### ISSUE THREAD

**Issue by sqsec** [yuyan-sec/Doraemon#4]
安装一直显示错误 ，

**Comment by yuyan-sec** [comment]
@Nexolanta 显示什么错误，没图我也不知道啊。是不是没创建目录和文件

**Comment by sqsec** [comment]
大佬 我截图发你看看  我也不知道什么报错
![image](https://user-images.githubusercontent.com/73454853/210255095-24d95460-2a4a-4aea-ac93-92780b186c27.png)
![image](https://user-images.githubusercontent.com/73454853/210255366-79e2321f-d64f-444c-8500-fd0161d5969e.png)

**Comment by sqsec** [comment]
我用java启动会这样哦
![image](https://user-images.githubusercontent.com/73454853/210255607-c00c4895-4d3b-4b4c-b4ee-35676f077ea6.png)

**Comment by yuyan-sec** [comment]
@Nexolanta 两个yaml的内容是否对，怎么看着好像乱码了。单独启动也需要这两个文件，因为是读取这两个yaml的内容，可以看看 [README.md](https://github.com/yuyan-sec/Doraemon#readme) 是怎么写的

**Comment by sqsec** [comment]
那个我没有写内容  就是先运行看下是否有问题 一定要写内容才能运行吗

**Comment by sqsec** [comment]
大佬你发个联系方式呗  我私聊你

**Comment by yuyan-sec** [comment]
@Nexolanta 是要内容的，没读取到内容java就报错了，我的wx 我就是我的id
