### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by alex123-2star** [yuyan-sec/Doraemon#6]

**Comment by yuyan-sec** [comment]
什么问题，发下截图和报错信息

**Comment by alex123-2star** [comment]
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/63630525/217271083-4b8b8aca-2079-4550-9d93-d00c63034690.png">
这里注释掉
<img width="804" alt="image" src="https://user-images.githubusercontent.com/63630525/217271331-bca0cc25-3da8-455b-bc5c-7c922414b105.png">
下面可以实现
            // 获取剪贴板中的内容
            String text="";
            Transferable trans = clip.getContents(null);
            if (trans != null) {
                // 判断剪贴板中的内容是否支持文本
                if (trans.isDataFlavorSupported(DataFlavor.stringFlavor)){
                    try {
                        // 获取剪贴板中的文本内容
                        text = (String) trans.getTransferData(DataFlavor.stringFlavor);
                        stdout.println(text);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
            }
            String script = "tell application \"Terminal\"";
            script += "\n do script \""+text+"\"";
            script += "\n end tell";
            ProcessBuilder pb = new ProcessBuilder("osascript", "-e", script);
            pb.inheritIO();
            stdout.println(script);
            try {
                pb.start();
            } catch (IOException e) {
                stdout.println(e.getMessage());
            }

**Comment by alex123-2star** [comment]
`            // 获取剪贴板中的内容
            String text="";
            Transferable trans = clip.getContents(null);
            if (trans != null) {
                // 判断剪贴板中的内容是否支持文本
                if (trans.isDataFlavorSupported(DataFlavor.stringFlavor)){
                    try {
                        // 获取剪贴板中的文本内容
                        text = (String) trans.getTransferData(DataFlavor.stringFlavor);
                        stdout.println(text);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
            }
            String script = "tell application \"Terminal\"";
            script += "\n do script \""+text+"\"";
            script += "\n end tell";
            ProcessBuilder pb = new ProcessBuilder("osascript", "-e", script);
            pb.inheritIO();
            stdout.println(script);
            try {
                pb.start();
            } catch (IOException e) {
                stdout.println(e.getMessage());
            }
`

**Comment by alex123-2star** [comment]
这样mac里面就可以用了

**Comment by yuyan-sec** [comment]
感谢师傅的指点。主要我没有mac，不太好测试。看看什么时候有空安装一个虚拟机来测试一下

**Comment by alex123-2star** [comment]
可以加个微信吗

**Comment by yuyan-sec** [comment]
可以，我的WX就是我的用户名
