### ISSUE TITLE
提个需求

### ISSUE THREAD

**Issue by komomon** [yuyan-sec/Doraemon#7]
可以在当前burp目录下新建个目录生成配置文件吗，这样迁移的时候方便，换个环境不用重新配置，更加便捷，HaE是可以记住上次配置的目录的。

**Comment by yuyan-sec** [comment]
之前的版本就是在Burp目录创建文件，但是linux有时候权限不够就需要自己手动创建。HaE 现在不是也在 用户/.config/HaE 目录下吗

**Comment by yuyan-sec** [comment]
@komomon 更新了 [1.0.3.1](https://github.com/yuyan-sec/Doraemon/releases/tag/1.0.3.1) 会优先访问 Burpsuite目录下的 DAM 目录和配置文件，但是不会创建。这样把配置放在Burpsuite就可以使用了。如果不存在就会在 /用户/.config/ 下创建

**Comment by komomon** [comment]
> @komomon 更新了 [1.0.3.1](https://github.com/yuyan-sec/Doraemon/releases/tag/1.0.3.1) 会优先访问 Burpsuite目录下的 DAM 目录和配置文件，但是不会创建。这样把配置放在Burpsuite就可以使用了。如果不存在就会在 /用户/.config/ 下创建

万分感谢，star了

**Comment by xkhl-yyds** [comment]
![image](https://user-images.githubusercontent.com/83859223/218012093-18b2d9eb-f2e5-4790-a399-43e4b0d97dfa.png)
中文乱码，怎么办

**Comment by yuyan-sec** [comment]
@yosel-yh 

1. 检查配置文件是否为 utf-8 编码
2. Burpsutie 是否为 utf-8 启动的： -Dfile.encoding=utf-8
