### ISSUE TITLE
[ bug ] 执行命令报错

### ISSUE THREAD

**Issue by enomothem** [yuyan-sec/Doraemon#8]
Windows10
右键发送到cmd ping命令显示如下
C:\burpsuite_pro_v2022.12>^V

**Comment by yuyan-sec** [comment]
@enomothem 截图看看配置是怎么写的

**Comment by enomothem** [comment]
解决方法：cmd属性编辑关闭使用旧版控制台UI即可。

**Comment by enomothem** [comment]
因为旧版的不支持Ctrl 模式
