### ISSUE TITLE
[ 优化 ] 添加http url的变量

### ISSUE THREAD

**Issue by enomothem** [yuyan-sec/Doraemon#9]
一个请求包的目标中，我们需要的基本是 http[s]://host:port/path

{request} 适用于整个请求包
{host} 对一个域名或IP进行提取
{url} 完整的 http请求url
但是我在使用dirsearch 的时候，这三个中，只有host最适合，但出现端口不是默认80的时候，比如8001，就不会带上端口进行扫描。
能否做到既要端口，又不要path的http url呢
http://example.com:8001
这样就更好了

**Comment by enomothem** [comment]
![image](https://user-images.githubusercontent.com/45089051/222963339-b46e6d43-d9bc-4d80-9941-74d717a43240.png)
就像这样，在burpsuite中的目标这里。
新增一个{target}提取请求包中 http://{domain}:{port} 我的大概思路就是这样

**Comment by yuyan-sec** [comment]
@enomothem {url}  url 就是可以获取到端口的

![1](https://user-images.githubusercontent.com/43353917/224608187-f6550fc3-8e0b-46ce-aa82-86f39dea6663.png)

**Comment by enomothem** [comment]
是的，{url}有端口，但会把/path/path/path 目录也携带上 ，而{target}只是少了端口。
我目前的解决方法就是，在配置参数的时候，直接把 -u 参数放置最后，然后改一改端口就可以了。
当然要是能增加一个也是不错的啦

**Comment by yuyan-sec** [comment]
@enomothem 下载 1.0.5 版本，我把 {target} 的端口加上了

**Comment by enomothem** [comment]
qq上发给我1192045710谢谢

**Comment by enomothem** [comment]
那太好了
